<?php

namespace Database\Seeders;

use App\Models\Work;
use Illuminate\Database\Seeder;

class WorksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            //////////////////////// HTML/CSS //////////////////////////
            [
                'title' => 'Smitler',
                'desc' => 'Верска салона красоты с Bootstrap, SASS, Gulp',
                'img' => 'img/smitler-min.png',
                'github_link' => 'https://github.com/Belchenkov/Smitler',
                'preview_link' => 'https://nimb.ws/2ojO4l',
                'demo_link' => 'http://smirler-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Portfolio SASS',
                'desc' => 'Верстка сайта-портфолио с SCSS, Flexbox, Grid System',
                'img' => 'img/portfolio_sass-min.png',
                'github_link' => 'https://github.com/Belchenkov/portfolio-sass',
                'preview_link' => 'https://nimbusweb.me/s/share/5609357/x48vlxdvt1oqy0z3x3ii',
                'demo_link' => 'http://portfolio-sass-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'NewsGird',
                'desc' => 'Верстка сайта на Grid System',
                'img' => 'img/news_grid-min.png',
                'github_link' => 'https://github.com/Belchenkov/news_grid',
                'preview_link' => 'https://nimb.ws/HWwbBm',
                'demo_link' => 'http://news-grid-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Sushi',
                'desc' => 'Адаптивная верстка на CSS Framework Bootstrap 4',
                'img' => 'img/sushi-min.png',
                'github_link' => 'https://github.com/Belchenkov/sushi-bootstrap4',
                'preview_link' => 'https://radikal.ru/video/n6ujfNdpAMn',
                'demo_link' => 'https://sushi-bootstrap-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'BlueRex',
                'desc' => 'Адаптивная верстка на CSS Framework Bootstrap 4',
                'img' => 'img/blueRex.png',
                'github_link' => 'https://github.com/Belchenkov/blueRex',
                'preview_link' => 'https://radikal.ru/video/i1t3oOLayoj',
                'demo_link' => 'http://blue-rex-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Gramdma\'s',
                'desc' => 'Адаптивная верстка на CSS Framework Bootstrap 4',
                'img' => 'img/gramdmas-min.png',
                'github_link' => 'https://github.com/Belchenkov/gramdmas',
                'preview_link' => 'https://radikal.ru/video/vjIwFnk6Z5J',
                'demo_link' => 'https://gramdmas-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Furniture',
                'desc' => 'Адаптивная верстка на CSS Framework Bootstrap 4',
                'img' => 'img/furniture-min.png',
                'github_link' => 'https://github.com/Belchenkov/furniture',
                'preview_link' => 'https://radikal.ru/video/mYh2XyN77i8',
                'demo_link' => 'http://furniture-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Portfolio Bootstrap 4',
                'desc' => 'Адаптивная верстка на CSS Framework Bootstrap 4',
                'img' => 'img/portfolio_bootstrap4-min.png',
                'github_link' => 'https://github.com/Belchenkov/portfolio_bootstrap4',
                'preview_link' => 'https://radikal.ru/video/UzAwCdbtpXN',
                'demo_link' => 'http://portfolio-bootstrap4-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Madmin',
                'desc' => 'Admin Panel on materialize.css',
                'img' => 'img/madmin-min.png',
                'github_link' => 'https://github.com/Belchenkov/madmin',
                'preview_link' => 'https://radikal.ru/video/cQptYN7ZGx3',
                'demo_link' => 'http://madmin-ab.surge.sh',
                'category_id' => 1,
            ],
            [
                'title' => 'Quazzu',
                'desc' => 'Landing Page on Materialize.css',
                'img' => 'img/quazzu-min.png',
                'github_link' => 'https://github.com/Belchenkov/Quazzu',
                'preview_link' => 'https://radikal.ru/video/Jf9Tfpvr2RZ',
                'demo_link' => 'http://quazzu-ab.surge.sh',
                'category_id' => 1,
            ],
            //////////////////////// Javascript //////////////////////////
            [
                'title' => 'Expense Tracker',
                'desc' => 'Keep track of income and expenses. Add and remove items and save to local storage',
                'img' => 'img/expense_tracker_js.png',
                'github_link' => 'https://github.com/Belchenkov/expense_tracker_js',
                'preview_link' => 'https://radikal.ru/video/unyldKI4ag1',
                'demo_link' => 'http://expense-tracker-js-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Expense Tracker',
                'desc' => 'Keep track of income and expenses. Add and remove items and save to local storage',
                'img' => 'img/meal_finder_js.png',
                'github_link' => 'https://github.com/Belchenkov/meal_finder_js',
                'preview_link' => 'https://radikal.ru/video/oarsxEbLJEv',
                'demo_link' => 'http://meal-finder-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Music Player',
                'desc' => 'Create beautiful UI to play music stored in the "music folder" using the HTML5 audio API',
                'img' => 'img/music_player_js.png',
                'github_link' => 'https://github.com/Belchenkov/music_player_js',
                'preview_link' => 'https://radikal.ru/video/A7qYK0Ct5bJ',
                'demo_link' => 'http://music-player-js-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Hangman Game',
                'desc' => 'Select a letter to figure out a hidden word in a set amount of chances',
                'img' => 'img/handman.png',
                'github_link' => 'https://github.com/Belchenkov/hangman_game',
                'preview_link' => 'https://radikal.ru/video/1mxIpdFTLCC',
                'demo_link' => 'http://handman-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Movie Seat Booking',
                'desc' => 'Display movie choices and seats in a theater to select from in order to purchase tickets',
                'img' => 'img/movie-seat-booking.png',
                'github_link' => 'https://github.com/Belchenkov/movie_seat-booking_js',
                'preview_link' => 'https://radikal.ru/video/TQWLqXiNyIe',
                'demo_link' => 'http://movie-seat-booking-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Custom Video Player',
                'desc' => 'Custom video player using the HTML5 video element and its JavaScript API with a custom design',
                'img' => 'img/custom-video-player.png',
                'github_link' => 'https://github.com/Belchenkov/js-video-timer',
                'preview_link' => 'https://radikal.ru/video/xzDDJbtLv8x',
                'demo_link' => 'http://custom-video-player-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Exchange Rate Calculator',
                'desc' => 'Select countries to get the exchange rate for a specific amount',
                'img' => 'img/exchange_calc.png',
                'github_link' => 'https://github.com/Belchenkov/exchange-rate-calc',
                'preview_link' => 'https://radikal.ru/video/K6JD1VR2pxX',
                'demo_link' => 'http://exchange_rate_calc-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Speech Text Reader',
                'desc' => 'A text to speech app for non-verbal people. Pre-made buttons and custom text speech.',
                'img' => 'img/text_speech_reader.png',
                'github_link' => 'https://github.com/Belchenkov/speech_text_reader_js',
                'preview_link' => 'https://radikal.ru/video/l9drNIghfA5',
                'demo_link' => 'http://text-speech-reader.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Breakout Game',
                'desc' => 'Game where you control a paddle with the arrow keys to bounce a ball up to break bricks.',
                'img' => 'img/breackout_game_js.png',
                'github_link' => 'https://github.com/Belchenkov/breakout_game',
                'preview_link' => 'https://radikal.ru/video/Q6epddLtZpV',
                'demo_link' => 'http://breakout-game-ab.surge.sh',
                'category_id' => 2,
            ],
            [
                'title' => 'Speed Typer Typing Game',
                'desc' => 'Game to beat the clock by typing random words',
                'img' => 'img/typing_game_js.png',
                'github_link' => 'https://github.com/Belchenkov/typing_game_js',
                'preview_link' => 'https://radikal.ru/video/4K0PPC3QPXB',
                'demo_link' => 'http://speed-typing-game-ab.surge.sh',
                'category_id' => 2,
            ],
            //////////////////////// Node.js //////////////////////////
             [
                'title' => 'Story Books',
                'desc' => 'App for manage Stories on Node.js/Express.js',
                'img' => 'img/story_books-min.png',
                'github_link' => 'https://github.com/Belchenkov/storyBooks',
                'preview_link' => 'https://radikal.ru/video/hQCctH7enYq',
                'demo_link' => 'https://story-books-nodejs-ab.herokuapp.com',
                'category_id' => 3,
            ],
            [
                'title' => 'Node VidJot',
                'desc' => 'App to create video ideas(Node.js, Express.js, MongoDB, Bootstrap 4',
                'img' => 'img/vidjot-min.png',
                'github_link' => 'https://github.com/Belchenkov/nodeVidJot',
                'preview_link' => 'https://radikal.ru/video/YLRRB2hiKU8',
                'demo_link' => 'https://node-vid-jot-ab.herokuapp.com',
                'category_id' => 3,
            ],
            [
                'title' => 'Chat Vue Node',
                'desc' => 'App to create video ideas(Node.js, Express.js, MongoDB, Bootstrap 4',
                'img' => 'img/node_vue_chat-min.png',
                'github_link' => 'https://github.com/Belchenkov/vue_node_chat_room',
                'preview_link' => '',
                'demo_link' => 'Chat on Node.js/Vue.js/Materialize.css',
                'category_id' => 3,
            ],
            [
                'title' => 'DevCamper',
                'desc' => 'Backend API for DevCamper application',
                'img' => 'img/devcamper_node.png',
                'github_link' => 'https://github.com/Belchenkov/devcamper_nodejs',
                'preview_link' => '',
                'demo_link' => '',
                'category_id' => 3,
            ],
            /////////////////////////// Angular \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'Mean Orders',
                'desc' => 'Full-stack app on MongoDB, Express.js, Angular 6, Node.js (MEAN)',
                'img' => 'img/mean-orders-min.png',
                'github_link' => 'https://github.com/Belchenkov/MEAN-Orders',
                'preview_link' => '',
                'demo_link' => 'https://quiet-plateau-84789.herokuapp.com',
                'category_id' => 4,
            ],
            [
                'title' => 'RecipeBook',
                'desc' => 'Recipe Book Application on Angular 7',
                'img' => 'img/recipe_book_angular-min.png',
                'github_link' => 'https://github.com/Belchenkov/recipeBookAngular7',
                'preview_link' => '',
                'demo_link' => 'https://recipe-book-ng-6c54f.firebaseapp.com',
                'category_id' => 4,
            ],
            [
                'title' => 'Домашняя бухгалтерия',
                'desc' => 'Приложение "Домашняя бухгалтерия" на Angular 10',
                'img' => 'img/home-money-min.png',
                'github_link' => 'https://github.com/Belchenkov/ng-money-keeper',
                'preview_link' => '',
                'demo_link' => '',
                'category_id' => 4,
            ],
            [
                'title' => 'Client Panel',
                'desc' => 'Finance Manager App on Angular 6, Firebase, Bootstrap 4, Font Awesome',
                'img' => 'img/clientpanel_angular.png',
                'github_link' => 'https://github.com/Belchenkov/clientPanelAng6',
                'preview_link' => '',
                'demo_link' => '',
                'category_id' => 4,
            ],
            /////////////////////////// React \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'ProShop eCommerce Platform',
                'desc' => 'eCommerce platform built with the MERN stack & Redux.',
                'img' => 'img/pro-shop.png',
                'github_link' => 'https://github.com/Belchenkov/mern_shop',
                'preview_link' => '',
                'demo_link' => 'https://proshop-ab.herokuapp.com',
                'category_id' => 5,
            ],
            [
                'title' => 'DevConnector MERN',
                'desc' => 'Social network for develops on MERN Stack (MongoDB, Express.js, React.js, Node.js)',
                'img' => 'img/devconnector.png',
                'github_link' => 'https://github.com/Belchenkov/developer-connector-mern',
                'preview_link' => '',
                'demo_link' => 'https://cryptic-hamlet-49557.herokuapp.com',
                'category_id' => 5,
            ],
            [
                'title' => 'Client Panel React/Redux',
                'desc' => 'Finance App on React/Redux, Font-Awesome 5, Bootstrap 4, Firebase',
                'img' => 'img/client_panel_react.png',
                'github_link' => 'https://github.com/Belchenkov/clientPanelReactRedux',
                'preview_link' => '',
                'demo_link' => 'https://reactclientpanel-83c29.firebaseapp.com',
                'category_id' => 5,
            ],
            [
                'title' => 'React Man City',
                'desc' => 'Build a react project (Man City Team) with authentication, Material-UI, firebase',
                'img' => 'img/react_man_city.png',
                'github_link' => 'https://github.com/Belchenkov/react-man-city',
                'preview_link' => '',
                'demo_link' => 'https://man-city-d0dfa.firebaseapp.com',
                'category_id' => 5,
            ],
            [
                'title' => 'It Logger',
                'desc' => 'React app to track IT department tasks and issues.',
                'img' => 'img/react-it-logger.png',
                'github_link' => 'https://github.com/Belchenkov/react-man-city',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/it-logger',
                'category_id' => 5,
            ],
            [
                'title' => 'React Contact Keeper',
                'desc' => 'App for manage contacts',
                'img' => 'img/react-contact-keeper.png',
                'github_link' => 'https://github.com/Belchenkov/react_contact_keeper',
                'preview_link' => '',
                'demo_link' => 'https://react-contact-keeper.herokuapp.com',
                'category_id' => 5,
            ],
            /////////////////////////// Vue.js  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'Guitars PRO',
                'desc' => 'A SPA on Vue.js and Vuetify for Guitars',
                'img' => 'img/vue-guitars-min.png',
                'github_link' => 'https://github.com/Belchenkov/vuejsVuetifyCars',
                'preview_link' => '',
                'demo_link' => 'https://vuetifyguitars.firebaseapp.com/',
                'category_id' => 6,
            ],
            [
                'title' => 'Money Keeper Vue',
                'desc' => 'Create CRM app "Home MoneyKeeper" use vue.js, materialize.css',
                'img' => 'img/vue-crm.png',
                'github_link' => 'https://github.com/Belchenkov/money_crm_vuejs',
                'preview_link' => '',
                'demo_link' => 'https://vue-money-crm.firebaseapp.com',
                'category_id' => 6,
            ],
            [
                'title' => 'GameSpot Blog',
                'desc' => 'Blog of Games with admin panel, authentication & add new posts',
                'img' => 'img/gamespot_vue.png',
                'github_link' => 'https://github.com/Belchenkov/gamespot_vue',
                'preview_link' => '',
                'demo_link' => 'https://gamespot-989e1.firebaseapp.com',
                'category_id' => 6,
            ],
            [
                'title' => 'Domnoo Pizza',
                'desc' => 'Landing Pizza-Shop on Vue.js',
                'img' => 'img/domnoo_vue.png',
                'github_link' => 'https://github.com/Belchenkov/domnoo_vue',
                'preview_link' => '',
                'demo_link' => 'https://domnoo-8a782.firebaseapp.com',
                'category_id' => 6,
            ],
            /////////////////////////// Electron.js  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'Chat Electron',
                'desc' => 'Build a clone Discord app on React + Electron',
                'img' => '',
                'github_link' => 'https://github.com/Belchenkov/chat_electon_react',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/chat_electon_react',
                'category_id' => 7,
            ],
            [
                'title' => 'YouTube Stats App',
                'desc' => 'Build a native desktop app - pull YouTube channel info from an API with Angular/Electron',
                'img' => 'img/you_tube_stats_electron.png',
                'github_link' => 'https://github.com/Belchenkov/you_tube_stats_electron',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/you_tube_stats_electron/releases/tag/master',
                'category_id' => 7,
            ],
            [
                'title' => 'Image Shrink',
                'desc' => 'Desktop App for optimize images (use Electron.js)',
                'img' => 'img/image_shrink.png',
                'github_link' => 'https://github.com/Belchenkov/image-shrink-electron',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/image-shrink-electron/releases/tag/1.0.0',
                'category_id' => 7,
            ],
            [
                'title' => 'SysTop',
                'desc' => 'Create application on Electron.js for monitors your system CPU',
                'img' => 'img/sys_top_cpu_electron.png',
                'github_link' => 'https://github.com/Belchenkov/sys-top-electron',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/sys-top-electron/releases/tag/1.0.0',
                'category_id' => 7,
            ],
            [
                'title' => 'BugLogger React/Electron',
                'desc' => 'React/Electron app that uses a MongoDB Atlas database to keep track of logs',
                'img' => 'img/bug_logger_electron.png',
                'github_link' => 'https://github.com/Belchenkov/bug_logger_electron',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/bug_logger_electron/releases/tag/1.0.0',
                'category_id' => 7,
            ],
            /////////////////////////// Nuxt/Next  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'Nuxt SSR SPA',
                'desc' => 'Build server-side-rendered single-page-applications (SPAs)',
                'img' => 'img/nuxt-spa-ssr.png',
                'github_link' => 'https://github.com/Belchenkov/nuxt-ssr-spa',
                'preview_link' => '',
                'demo_link' => 'https://nuxt-ssr-spa.firebaseapp.com',
                'category_id' => 8,
            ],
            /////////////////////////// React Native  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'RN Shop App',
                'desc' => 'Build Shop App on React Native',
                'img' => 'img/rn-shop.png',
                'github_link' => 'https://github.com/Belchenkov/rn-shop',
                'preview_link' => 'https://radikal.ru/video/IiXTNB68yjL',
                'demo_link' => 'https://expo.io/@belchenkov/rn-shop',
                'category_id' => 9,
            ],
            [
                'title' => 'RN Meals App',
                'desc' => 'Build Meals App on React Native',
                'img' => 'img/rn-meals.png',
                'github_link' => 'https://github.com/Belchenkov/rn-meals',
                'preview_link' => '',
                'demo_link' => 'https://expo.io/@belchenkov/rn_meals_app',
                'category_id' => 9,
            ],
            [
                'title' => 'RN Self Blog',
                'desc' => 'Create Posts Blog with (Navigation, Redux, Camera) on React Native',
                'img' => 'img/rn_self_blog.png',
                'github_link' => 'https://github.com/Belchenkov/rn-self-blog',
                'preview_link' => '',
                'demo_link' => 'https://expo.io/@belchenkov/rn-self-blog',
                'category_id' => 9,
            ],
            [
                'title' => 'Guess Number App',
                'desc' => 'Build Game "Guess a Number" with React Native',
                'img' => 'img/rn_guess_number.png',
                'github_link' => 'https://github.com/Belchenkov/rn-guess-number',
                'preview_link' => '',
                'demo_link' => 'https://expo.io/@belchenkov/rn_guess_number',
                'category_id' => 9,
            ],
            /////////////////////////// PHP/Laravel  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
            [
                'title' => 'Movie App',
                'desc' => 'Create App "Movie App" use Laravel 7 & TMDb API.',
                'img' => 'img/laravel_movie.png',
                'github_link' => 'https://github.com/Belchenkov/laravel7_movie',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/laravel7_movie',
                'category_id' => 10,
            ],
            [
                'title' => 'LaraBoard',
                'desc' => 'Create a clone Avito on Laravel 5',
                'img' => 'img/.png',
                'github_link' => 'https://github.com/Belchenkov/laravel5-demo-board',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/laravel5-demo-board',
                'category_id' => 10,
            ],
            [
                'title' => 'DesignHouse',
                'desc' => 'Create Fullstack app "Design House" with use Nuxt.js, Laravel',
                'img' => 'img/.png',
                'github_link' => 'https://github.com/Belchenkov/design_house',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/design_house',
                'category_id' => 10,
            ],
            [
                'title' => 'Ng Laravel CRM',
                'desc' => 'Build CRM on Angular 11 & Laravel 8',
                'img' => 'img/ng_lara_crm.png',
                'github_link' => 'https://github.com/Belchenkov/ang_laravel_crm',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/ang_laravel_crm',
                'category_id' => 10,
            ],
            [
                'title' => 'PHP MVC Framework',
                'desc' => 'Build an application on top of that with user authentication, validation, CRUD functionality',
                'img' => 'img/php_mvc-min.png',
                'github_link' => 'https://github.com/Belchenkov/php_mvc_framework',
                'preview_link' => '',
                'demo_link' => 'https://github.com/Belchenkov/php_mvc_framework',
                'category_id' => 10,
            ]
        ];

        foreach ($data as $work) {
            Work::create($work);
        }
    }
}
